name: 评测

on:
  push:
    branches:
      - main
    paths:
      - main.c  # main.c被修改时触发

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      MY_URL: ${{ secrets.MY_URL }}
    steps:
      - name: 检出仓库
        uses: actions/checkout@v3
        
        
      - name: 安装依赖
        run: |
          if [ -z "${MY_URL}" ]; then
            exit 1  # 退出
          fi
          sudo apt-get update
          sudo apt-get install gcc python3
          pip3 install pandas

      - name: 测试
        run: |
          echo "Cloning URL: https://${MY_URL}"
          git clone https://${MY_URL}:x-oauth-basic@github.com/Firefly-fly/c-cpp_test.git
          cp c-cpp_test/test.py .
          python3 test.py
